# Generated by Django 3.0.4 on 2020-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.CharField(default='https://www.tresmonjitas.com/wp-content/uploads/2018/07/PlaceholderLogo.png', max_length=200)),
            ],
        ),
    ]
